
repos:

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.11.6
    hooks:
      - id: uv-sync
      - id: uv-lock
      
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.10
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ] # Live dangerously, add the --fix-unsafe flag.
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: write-documentation
        name: Sync project documentation.
        entry: python .python/scripts/write_documentation.py
        language: python
        additional_dependencies:
          - jinja2
        files: pyproject.toml
        stages: [pre-commit]
