
repos:

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.11.6
    hooks:
      - id: uv-sync
      - id: uv-lock
      - id: uv-export

  - repo: local
    hooks:
      - id: write-documentation
        name: Sync project documentation.
        entry: uv run python .python/write_documentation.py
        language: system
        additional_dependencies:
          - jinja2
        files: ^pyproject\.toml$
        stages: [pre-commit]
