name: Add ➕ Feature 🔧

on:
  push: 
    branches:
      - features

jobs:

  increment:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    
    - name: Checkout Project
      uses: actions/checkout@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install UV
      uses: astral-sh/setup-uv@v7
    
    - name: Dry Run Version Increment
      run: |
        uv version --bump alpha --dry-run

    - name: Version Increment Alpha Alone
      run: |
        uv version --bump alpha
    
    - name: Verify Version Changed
      run: git diff --exit-code pyproject.toml || echo "Version updated successfully"

    - name: Tag release
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        branch: tests
        commit_message: "Released $(uv version)"
        tag_name: "v$(uv version)"
  
