name: Add Test Set 🧪 to Development Branch.

on:
  pull_request: 
    branches: 
      - development
    types: closed

permissions:
  contents: write
  pull-requests: write
  
jobs:

  increment:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    
    steps:
    
    - name: Checkout Project
      uses: actions/checkout@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install UV
      uses: astral-sh/setup-uv@v7
    
    - name: Dry Run Version Increment
      id: is_development
      run: |
        uv version --bump dev --dry-run

    - name: Version Increment Dev Alone
      if: steps.is_development.outcome == 'success'
      run: |
        uv version --bump dev

    - name: Version Increment Patch as Dev 
      if: steps.is_development.outcome == 'failure'
      run: |
        uv version --bump minor --bump dev
    
    - name: Verify Version Changed
      run: git diff --exit-code pyproject.toml || echo "Version updated successfully"

    - name: Increment Minor Version
      id: version
      shell: bash
      run: |
        VERSION=$(uv version)
        echo "version=$VERSION" >> $GITHUB_OUTPUT 

    - name: Commit & Push Version Change
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: "chore: bump development version to ${{ steps.version.outputs.version }}"
        file_pattern: pyproject.toml
