
name: Spawn Release Canidate 🧪

on:
  pull_request:
    branches:
      - canidate
    types:
      - closed

jobs:

  increment:
  
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    permissions: write-all

    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Install UV
        uses: astral-sh/setup-uv@v7
      
      - name: Dry Run Version Increment
        run: |
          uv version --bump rc --dry-run

      - name: Version Increment
        run: |
          uv version --bump rc

      - name: Verify Version Changed
        run: git diff --exit-code pyproject.toml || echo "Version updated successfully"

      - name: Commit Version Increment 
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          branch: development
          commit_message: "Released $(uv version)"
          tag_name: "v$(uv version)"

  create_release_canidate:
  
    runs-on: ubuntu-latest
    needs: increment
    steps:
    
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      
      - name: Install UV
        uses: astral-sh/setup-uv@v7
    
      - name: Create RC branch
        id: create_release_canidate_branch
        run: |
          git checkout -b v/$( uv version )
          git push origin v/$( uv version )

      - name: Create GitHub release
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: 'v$(uv version)',
              name: 'Release $(uv version)',
              draft: false,
              prerelease: false,
            })  
