name: Patch 🔧 Beta 🍏

on:
  push:
    branches:
      - beta

jobs:

  setup:
    name: Setup Dependencies
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
  
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
  
      - name: Install UV
        uses: astral-sh/setup-uv@v7
  
      - name: Install dependencies
        run: uv sync --locked --all-extras
  
      - name: Cache UV environment
        uses: actions/upload-artifact@v4
        with:
          name: uv-cache
          path: |
            .venv
            .uv
          retention-days: 1

  test:
    name: Run Tests
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
  
    steps:
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          persist-credentials: false
  
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
  
      - name: Install UV
        uses: astral-sh/setup-uv@v7
  
      - name: Restore UV environment
        uses: actions/download-artifact@v4
        with:
          name: uv-cache
  
      - name: Install Pre-Commit
        run: uv tool install pre-commit --with pre-commit-uv --force-reinstall
  
      - name: Install Hooks
        run: pre-commit install
  
      - name: Run Tests
        run: pre-commit run pytest --all-files
  
      - name: Uninstall Hooks
        run: pre-commit uninstall
  
  increment:
    name: Increment Version ⬆️
    needs: test
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
    
    steps:

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
    
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
  
      - name: Install UV
        uses: astral-sh/setup-uv@v7
  
      - name: Restore UV environment
        uses: actions/download-artifact@v4
        with:
          name: uv-cache

      - name: Dry Run Patch Version Increment
        run: uv version --bump patch --dry-run

      - name: Patch Version Increment
        run: uv version --bump patch

      - name: Stage Version Changes
        run: git add pyproject.toml

      - name: Commit Version Changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Auto-incremented; Released Version $(uv version) ."
          
