name: Prepare PyPI Production Release

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Validate Distribution ✅
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      
    steps:
    
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
      
      - name: Install UV
        uses: astral-sh/setup-uv@v7

      - name: Install YQ && Append Requirements to pre-commit Pytest Hook
        id: append_requirements
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y yq && ${PWD}/.sh/scripts/append_requirements.sh && sudo apt purge yq
      
      - name: Install Pre-Commit
        run: uv tool install pre-commit --with pre-commit-uv --force-reinstall
  
      - name: Install Hooks
        run: pre-commit install
  
      - name: Run Tests
        run: pre-commit run pytest --all-files

      - name: Clean Up
        run: pre-commit uninstall

  build:
    name: Build Distribution 📦; Cache Distribution ⬆️
    needs: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"
  
      - name: Install UV
        uses: astral-sh/setup-uv@v7

      - name: Build Distribution
        run: uv build

      - name: Store Distribution Packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
          retention-days: 1
  close:
    name: Close ❎ Pull Request ☑️ 
    needs: build
    runs-on: ubuntu-latest
    steps:    
      - name: Auto-Merge Pull Request
        if: success()
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
