name: Validate

on:
  pull_request:
    branches:
      - development

jobs:
  test:
    name: Install Dependencies, Run Pytest
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout Project
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install UV
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --locked --all-extras

      - name: Install Pre-Commit
        run: uv tool install pre-commit --with pre-commit-uv --force-reinstall

      - name: Install Hooks
        run: pre-commit install

      - name: Run Tests
        run: pre-commit run pytest --all-files

      - name: Uninstall Hooks
        run: pre-commit uninstall
      
  increment:
    name: Increment Version
    needs: test
  
    permissions: write-all
  
    runs-on: ubuntu-latest
  
    steps:

      - name: Dry Run Increment
        run: uv version --bump minor --dry-run && uv version --bump patch --dry-run

      - name: Extract Branch Name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      
      - name: Version Incremeant Feature
        if: ${{ steps.extract_branch.outputs.branch == 'features' }}
        run: uv version --bump minor

      - name: Version Incremeant Patch
        if: ${{ steps.extract_branch.outputs.branch == 'patches' }}
        run: uv version --bump patch

      - name: Incorperate Version Change Into Version Control
        shell: bash
        run: git add pyproject.toml

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Auto-incremented Version.  
      
